name: SNN HW/SW Match CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps (apt)
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator make g++ python3 python3-pip

      - name: Install Python deps (pip)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install numpy

      - name: Run make test (build & sim & compare)
        run: |
          make veryclean || true
          make test

      - name: Assert perfect match (diff=0)
        run: |
          python3 - <<'PY'
          import numpy as np, sys
          a = np.loadtxt('artifacts/diff_mask.csv', delimiter=',', dtype=int)
          diffs = int(a.sum())
          print(f"[ASSERT] diffs={diffs}")
          sys.exit(0 if diffs==0 else 1)
          PY

      - name: Upload artifacts for debugging (on failure only)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug
          path: |
            artifacts/**/*.csv
            artifacts/**/*.mem
            artifacts/**/*.hex
            obj_dir/**
